### PR TITLE
Add Kazakh translations

### PR DESCRIPTION
**Pull request by KtlTheBest**
Decided to add some translations in Kazakh language. I hope you don't mind.

Any questions, comments and suggestions are welcome.

Best regards,
KtlTheBest

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Thank you

**Comment by MangelMaxime** [comment]
I don't know what symbol you used to indent the code, but you should use 4 spaces for indentation when using F#.

I fixed it in the main branch.

**Comment by KtlTheBest** [comment]
@MangelMaxime Thank you, and sorry. I used a Github's Web editor, didn't know it didn't use spaces. I'm an OCaml hobbyist with passing experience in F# :sweat_smile:.

I assume that I don't need to create a new pull request with fixed indentation, right?

Best regards,
KtlTheBest

**Comment by MangelMaxime** [comment]
No problem.

> I assume that I don't need to create a new pull request with fixed indentation, right?

No action needed from you, I fixed it directly in main when I saw the CI fails

**Pull request merged**
